聚合就是分组嘛

In [2]:
import pandas as pd

bios = pd.read_csv("./data/bios.csv")

In [3]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
bios["born_region"].value_counts()

born_region
England            4824
Ontario            1710
California         1634
Budapest           1447
New South Wales    1120
                   ...
Kalasin               1
Iğdır                 1
Ağstafa               1
Sihanoukville         1
Vĩnh Long             1
Name: count, Length: 2554, dtype: int64

In [5]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [6]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts().tail(20)

born_region
Vermont           68
Mississippi       66
Alabama           64
Tennessee         62
Kentucky          62
Nebraska          60
Rhode Island      56
Montana           55
Maine             50
South Carolina    50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

In [8]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [10]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [13]:
coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [14]:
coffee.groupby("Coffee Type")["Units Sold"].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [15]:
coffee["Price"] = coffee["Coffee Type"].apply(lambda x: 4.99 if x == "Espresso" else 5.99)

In [ ]:
#groupby算出中间过程，agg传入字典，指定不同聚合函数的结果是求啥，平均还是求和还是啥
coffee.groupby("Coffee Type").agg({
    "Units Sold":"sum",
    "Price":"mean"})

             Units Sold  Price
Coffee Type
Espresso            265   4.99
Latte               195   5.99

In [ ]:
coffee.groupby("Coffee Type","Day").agg({
    "Units Sold":"sum",
    "Price":"mean"})