1.Introduction to DataFrame

In [2]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

#columns 指定列名,是元素之外的额外指定的，注意在二维方括号外面但是在括号里面
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns = ["A","B","C"])

1.1 展示show

In [ ]:
#显示前五行
df.head()
#最左边一列的0，1，2，被叫做索引index

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#head里可以指定看前i行
df.head(1)

   A  B  C
0  1  2  3

In [10]:
df.head(2)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df.tail(2)

   A  B  C
1  4  5  6
2  7  8  9

In [13]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

1.2 index show

In [ ]:
#pandas把index设计为一种数据类型，rangeindex是index的一种
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
#tolist()
df.index.tolist()

[0, 1, 2]

In [20]:
df.index = ["x","y","z"]
df.index

Index(['x', 'y', 'z'], dtype='str')

1.3 more information

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
#25%和75%代表第一四分位和第三四分位，first quartile和third quartile
#平均数，然后（第一个数+平均数）/2  
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
#每一列唯一值的数量
df.nunique()

A    3
B    3
C    3
dtype: int64

In [24]:
df["A"].nunique()

3

In [25]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [26]:
df.shape

(3, 3)

In [27]:
df.size

9

In [31]:
df["zz"] = [10,11,12]
df

   A  B  C  zz
x  1  2  3  10
y  4  5  6  11
z  7  8  9  12

In [ ]:
#为了避免行列重名，加了一个axis,axis = 1代表列，axis = 0代表行;
# 此外，axis在对行或是对列操作时，默认是axis = 0
df = df.drop("zz",axis = 1)
#或是df.drop("zz",axis = 1,inplace = True)
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

2. loading in dataframes from files

1. 读取csv

In [10]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
#或是coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
#这是github点开csv文件之后，点右上角的raw，然后复制链接，效果是一样的

In [35]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

2. 读取parquet

In [ ]:
#这个库里包含了对parquet等文件的IO操作的支持，只有pandas不能读取parquet文件
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.3 MB ? eta -:--:--
    --------------------------------------- 0.5/27.3 MB 1.1 MB/s eta 0:00:25
   - -------------------------------------- 0.8/27.3 MB 1.1 MB/s eta 0:00:24
   - -------------------------------------- 1.0/27.3 MB 1.2 MB/s eta 0:00:23
   - -------------------------------------- 1.3/27.3 MB 1.2 MB/s eta 0:00:23
   -- ------------------------------------- 1.6/27.3 MB 1.2 MB/s eta 0:00:23
   -- ------------------------------------- 1.8/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.1/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.4/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.6/27.3 MB 1.2 MB/s eta 0:00:22
   ---- ----------------------------------- 2.9/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.1/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.1/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.4/27.3 MB 1.2 MB/s eta 0:00:21
   ----- ---------------------------------- 3.7/27.3 MB 1.2 MB/s eta 0:00:21
   ----- ---------------------------------- 3.9/27.3 MB 1.2 MB/s eta 0:00:21
   ------ --------------------------------- 4.2/27.3 MB 1.2 MB/s eta 0:00:20
   ------ --------------------------------- 4.5/27.3 MB 1.2 MB/s eta 0:00:20
   ------ --------------------------------- 4.7/27.3 MB 1.2 MB/s eta 0:00:20
   ------- -------------------------------- 5.0/27.3 MB 1.2 MB/s eta 0:00:20
   ------- -------------------------------- 5.2/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 5.5/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 5.8/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 6.0/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 6.0/27.3 MB 1.2 MB/s eta 0:00:19
   --------- ------------------------------ 6.3/27.3 MB 1.2 MB/s eta 0:00:19
   --------- ------------------------------ 6.6/27.3 MB 1.2 MB/s eta 0:00:18
   --------- ------------------------------ 6.8/27.3 MB 1.2 MB/s eta 0:00:18
   ---------- ----------------------------- 7.1/27.3 MB 1.2 MB/s eta 0:00:18
   ---------- ----------------------------- 7.3/27.3 MB 1.2 MB/s eta 0:00:18
   ----------- ---------------------------- 7.6/27.3 MB 1.2 MB/s eta 0:00:18
   ----------- ---------------------------- 7.9/27.3 MB 1.2 MB/s eta 0:00:17
   ----------- ---------------------------- 8.1/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.4/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.4/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.7/27.3 MB 1.1 MB/s eta 0:00:17
   ------------- -------------------------- 8.9/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.2/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.4/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.4/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 9.7/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 10.0/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 10.2/27.3 MB 1.1 MB/s eta 0:00:16
   --------------- ------------------------ 10.5/27.3 MB 1.1 MB/s eta 0:00:15
   --------------- ------------------------ 10.7/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.0/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.3/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.5/27.3 MB 1.1 MB/s eta 0:00:14
   ----------------- ---------------------- 11.8/27.3 MB 1.1 MB/s eta 0:00:14
   ----------------- ---------------------- 12.1/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.3/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.3/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.6/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------ --------------------- 12.8/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.1/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.4/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.6/27.3 MB 1.1 MB/s eta 0:00:13
   -------------------- ------------------- 13.9/27.3 MB 1.1 MB/s eta 0:00:12
   -------------------- ------------------- 14.2/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.4/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.7/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.9/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.2/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.5/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.5/27.3 MB 1.1 MB/s eta 0:00:11
   ----------------------- ---------------- 15.7/27.3 MB 1.1 MB/s eta 0:00:11
   ----------------------- ---------------- 16.0/27.3 MB 1.1 MB/s eta 0:00:10
   ----------------------- ---------------- 16.3/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 16.5/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 16.8/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 17.0/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------- -------------- 17.3/27.3 MB 1.1 MB/s eta 0:00:09
   ------------------------- -------------- 17.6/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 17.8/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 17.8/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 18.1/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 18.4/27.3 MB 1.1 MB/s eta 0:00:08
   --------------------------- ------------ 18.6/27.3 MB 1.1 MB/s eta 0:00:08
   --------------------------- ------------ 18.9/27.3 MB 1.1 MB/s eta 0:00:08
   ---------------------------- ----------- 19.1/27.3 MB 1.1 MB/s eta 0:00:08
   ---------------------------- ----------- 19.4/27.3 MB 1.1 MB/s eta 0:00:07
   ---------------------------- ----------- 19.7/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 19.9/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 20.2/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 20.4/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------ --------- 20.7/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------ --------- 21.0/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.2/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.2/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.5/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.8/27.3 MB 1.1 MB/s eta 0:00:05
   -------------------------------- ------- 22.0/27.3 MB 1.1 MB/s eta 0:00:05
   -------------------------------- ------- 22.3/27.3 MB 1.1 MB/s eta 0:00:05
   --------------------------------- ------ 22.5/27.3 MB 1.1 MB/s eta 0:00:05
   --------------------------------- ------ 22.8/27.3 MB 1.1 MB/s eta 0:00:04
   --------------------------------- ------ 23.1/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.3/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.6/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.9/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.1/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.4/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.4/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 24.6/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 24.9/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 25.2/27.3 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 25.4/27.3 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 25.7/27.3 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 26.0/27.3 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 26.2/27.3 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  26.7/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 1.1 MB/s  0:00:23
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
results = pd.read_parquet("./data/results.parquet")

In [4]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

2.3 读取excel

In [7]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
olympics_data = pd.read_excel("./data/olympics-data.xlsx")

In [3]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
#excel文件里有多个sheet（就是下面的那个可以取名增加的），默认是第一个sheet，如果想要指定sheet，可以用sheet_name参数
olympics_data1 = pd.read_excel("./data/olympics-data.xlsx",sheet_name = "results")

In [5]:
olympics_data1.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [ ]:
bios = pd.read_csv("./data/bios.csv")

2.4 resave转换格式

In [ ]:
#bios.to_parquet
#bio.to_csv
#bio.to_excel

3. accessing data with pandas

3.1 看头部/尾部/随机数

In [12]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
#看全部的数据
coffee
#其他的语法 print(coffee) 或是 display(coffee) 都可以显示全部数据,在当前的环境里也可以显示

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
#如果觉得数据开头结尾不是很重要并且数据量很大或是很分散，可以用sample随机抽取一些行来看看
# 括号里是采样指定的行数
coffee.sample(10)
#重复执行结果不一样，因为是随机抽取的

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
6    Thursday    Espresso          40
13     Sunday       Latte          35
8      Friday    Espresso          45
0      Monday    Espresso          25
11   Saturday       Latte          35
9      Friday       Latte          35
3     Tuesday       Latte          20
2     Tuesday    Espresso          30
5   Wednesday       Latte          25

In [ ]:
coffee.sample(10,random_state = 1)
#random_state参数可以让每次随机抽取的结果一样，参数值可以是任意整数，
# 或者是None（默认值），如果是None，每次抽取的结果都不一样
#如果是固定值，每次抽取的结果都一样
#底层逻辑是随机数种子
#可以叫做repeatable或是deterministic确定性的

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

3.2 具体取行或者列

In [ ]:
#loc iloc